### ISSUE TITLE
please let me know when the final version is available

### ISSUE THREAD

**Issue by danielskatz** [katerena/diss#1]
Hi

If you can let me know when the final version of this is done, I would appreciate it.  I would like to circulate it in the WSSSPE community (http://wssspe.researchcomputing.org.uk).  It appears to be very relevant to us.

Thanks,
Dan

**Comment by ksen0** [comment]
Will do! I'll ping along this issue and close it when I have the final version on here.
Thanks for reaching out, Dan! Feel free to also reach me at  kuksenok at uw dot edu

**Comment by ksen0** [comment]
Short version: https://medium.com/hci-design-at-uw/code-work-in-science-how-it-changes-and-why-it-matters-how-we-talk-about-change-fecd33471b0#.bpk7seb2w

Long version: https://github.com/katerena/diss/blob/master/output.pdf
